logout:
    path: /logout
app_room103:
    resource: "@AppRoom103Bundle/Controller/"
    type:     annotation
    prefix:   /


app:
    resource: "@AppBundle/Controller/"
    type:     annotation
account_register:
    path:     /register
    defaults: { _controller: AppRoom103Bundle:Account:register }

account_create:
    path:     /register/create
    defaults: { _controller: AppRoom103Bundle:Account:create }
