# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
    encoders:
            Symfony\Component\Security\Core\User\User: plaintext
            App\Room103Bundle\Entity\User: plaintext


    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        our_db_provider:
          entity:
            class: AppRoom103Bundle:User
            property: username
                    # if you're using multiple entity managers
                    # manager_name: customer

        in_memory:
            memory:
                users:
                    admin:
                        password: admin
                        roles: 'ROLE_ADMIN'

    firewalls:

        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            logout:
                        path:   /logout
                        target: /news
                        invalidate_session: false
                        delete_cookies:
                            a: { path: null, domain: null }
                            b: { path: null, domain: null }

            anonymous: ~
            # activate different ways to authenticate

            http_basic: ~
            # http://symfony.com/doc/current/book/security.html#a-configuring-how-your-users-will-authenticate

            form_login:
              login_path: /login
              check_path: /login_check
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html




